# 配置文件

DAILY_TIME: "08:00" # 每日定时发送时间。该时间为系统时间，如果当前系统时间不为北京时间需要自行进行换算

START_DATE: "2022-08-12" # 纪念日
CITY: "南阳"

BIRTHDAY:
  - "08-14"

APP_ID: "wxcdc8a96133af0fd9"
APP_SECRET: "08ba49888e95dfc35dab73f9c8340c4d"

USER_ID: 
  - "oQ8d-57Isxyvm7WmIR-VUMKvzxmk"
  - "oQ8d-58xbbJFAAvioiPQan-ERa3A" # 你可以通过配置多个USER_ID来设置多个接受者，如果接受者只有一人删除本行即可
TEMPLATE_ID: "FXPfGFZqCOmQgbFcU1EBdWNtfny0E5Hkh7IUEI_UyeA"
